/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GeocacheNote from '../model/GeocacheNote';

/**
* GeocacheNotes service.
* @module api/GeocacheNotesApi
* @version v1
*/
export default class GeocacheNotesApi {

    /**
    * Constructs a new GeocacheNotesApi. 
    * @alias module:api/GeocacheNotesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the geocacheNotesDeleteNote operation.
     * @callback module:api/GeocacheNotesApi~geocacheNotesDeleteNoteCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a geocache note for the calling user
     * This method will return no content.
     * @param {String} referenceCode The identifier of the geocache (ex: GC25)
     * @param {String} apiVersion The requested API version
     * @param {module:api/GeocacheNotesApi~geocacheNotesDeleteNoteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    geocacheNotesDeleteNote(referenceCode, apiVersion, callback) {
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling geocacheNotesDeleteNote");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling geocacheNotesDeleteNote");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v{api-version}/geocaches/{referenceCode}/notes', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the geocacheNotesUpsertNote operation.
     * @callback module:api/GeocacheNotesApi~geocacheNotesUpsertNoteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upsert a geocache note for the calling user
     * This method will return the upserted text.
     * @param {String} referenceCode The identifier of the geocache (ex: GC25)
     * @param {String} apiVersion The requested API version
     * @param {module:model/GeocacheNote} geocacheNote The geocache note text.
     * @param {module:api/GeocacheNotesApi~geocacheNotesUpsertNoteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    geocacheNotesUpsertNote(referenceCode, apiVersion, geocacheNote, callback) {
      let postBody = geocacheNote;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling geocacheNotesUpsertNote");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling geocacheNotesUpsertNote");
      }
      // verify the required parameter 'geocacheNote' is set
      if (geocacheNote === undefined || geocacheNote === null) {
        throw new Error("Missing the required parameter 'geocacheNote' when calling geocacheNotesUpsertNote");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'application/json-patch+json', 'application/x-www-form-urlencoded', 'text/json'];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v{api-version}/geocaches/{referenceCode}/notes', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
