/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.AttributeType = factory(root.GeocachingApiV10.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AttributeType model module.
   * @module model/AttributeType
   * @version v1
   */

  /**
   * Constructs a new <code>AttributeType</code>.
   * @alias module:model/AttributeType
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AttributeType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttributeType} obj Optional instance to populate.
   * @return {module:model/AttributeType} The populated <code>AttributeType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('hasYesOption')) {
        obj['hasYesOption'] = ApiClient.convertToType(data['hasYesOption'], 'Boolean');
      }
      if (data.hasOwnProperty('hasNoOption')) {
        obj['hasNoOption'] = ApiClient.convertToType(data['hasNoOption'], 'Boolean');
      }
      if (data.hasOwnProperty('yesIconUrl')) {
        obj['yesIconUrl'] = ApiClient.convertToType(data['yesIconUrl'], 'String');
      }
      if (data.hasOwnProperty('noIconUrl')) {
        obj['noIconUrl'] = ApiClient.convertToType(data['noIconUrl'], 'String');
      }
      if (data.hasOwnProperty('notChosenIconUrl')) {
        obj['notChosenIconUrl'] = ApiClient.convertToType(data['notChosenIconUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} hasYesOption
   */
  exports.prototype['hasYesOption'] = undefined;
  /**
   * @member {Boolean} hasNoOption
   */
  exports.prototype['hasNoOption'] = undefined;
  /**
   * @member {String} yesIconUrl
   */
  exports.prototype['yesIconUrl'] = undefined;
  /**
   * @member {String} noIconUrl
   */
  exports.prototype['noIconUrl'] = undefined;
  /**
   * @member {String} notChosenIconUrl
   */
  exports.prototype['notChosenIconUrl'] = undefined;



  return exports;
}));


