/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BulkFailure'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BulkFailure'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.BulkResponse = factory(root.GeocachingApiV10.ApiClient, root.GeocachingApiV10.BulkFailure);
  }
}(this, function(ApiClient, BulkFailure) {
  'use strict';




  /**
   * The BulkResponse model module.
   * @module model/BulkResponse
   * @version v1
   */

  /**
   * Constructs a new <code>BulkResponse</code>.
   * @alias module:model/BulkResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BulkResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BulkResponse} obj Optional instance to populate.
   * @return {module:model/BulkResponse} The populated <code>BulkResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('successes')) {
        obj['successes'] = ApiClient.convertToType(data['successes'], ['String']);
      }
      if (data.hasOwnProperty('failures')) {
        obj['failures'] = ApiClient.convertToType(data['failures'], [BulkFailure]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} successes
   */
  exports.prototype['successes'] = undefined;
  /**
   * @member {Array.<module:model/BulkFailure>} failures
   */
  exports.prototype['failures'] = undefined;



  return exports;
}));


