/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.HQPromotionMetadata = factory(root.GeocachingApiV10.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HQPromotionMetadata model module.
   * @module model/HQPromotionMetadata
   * @version v1
   */

  /**
   * Constructs a new <code>HQPromotionMetadata</code>.
   * @alias module:model/HQPromotionMetadata
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>HQPromotionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HQPromotionMetadata} obj Optional instance to populate.
   * @return {module:model/HQPromotionMetadata} The populated <code>HQPromotionMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pageTitle')) {
        obj['pageTitle'] = ApiClient.convertToType(data['pageTitle'], 'String');
      }
      if (data.hasOwnProperty('linkText')) {
        obj['linkText'] = ApiClient.convertToType(data['linkText'], 'String');
      }
      if (data.hasOwnProperty('linkSubText')) {
        obj['linkSubText'] = ApiClient.convertToType(data['linkSubText'], 'String');
      }
      if (data.hasOwnProperty('iconData')) {
        obj['iconData'] = ApiClient.convertToType(data['iconData'], 'String');
      }
      if (data.hasOwnProperty('relativeUrl')) {
        obj['relativeUrl'] = ApiClient.convertToType(data['relativeUrl'], 'String');
      }
      if (data.hasOwnProperty('campaignId')) {
        obj['campaignId'] = ApiClient.convertToType(data['campaignId'], 'Number');
      }
      if (data.hasOwnProperty('linkVisibleStartDateUtc')) {
        obj['linkVisibleStartDateUtc'] = ApiClient.convertToType(data['linkVisibleStartDateUtc'], 'Date');
      }
      if (data.hasOwnProperty('linkVisibleEndDateUtc')) {
        obj['linkVisibleEndDateUtc'] = ApiClient.convertToType(data['linkVisibleEndDateUtc'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Page title for the campaign.
   * @member {String} pageTitle
   */
  exports.prototype['pageTitle'] = undefined;
  /**
   * Text that should be displayed on the link/button leading to the campaign page.
   * @member {String} linkText
   */
  exports.prototype['linkText'] = undefined;
  /**
   * SubText that should be displayed on the link/button leading to the campaign page.
   * @member {String} linkSubText
   */
  exports.prototype['linkSubText'] = undefined;
  /**
   * Byte array containing the icon for the campaign in png
   * @member {String} iconData
   */
  exports.prototype['iconData'] = undefined;
  /**
   * Link off geocaching root for the campaign (\"/play/leaderboard\", \"/play/hqpromo/campaignname\" for example)
   * @member {String} relativeUrl
   */
  exports.prototype['relativeUrl'] = undefined;
  /**
   * Unique Campaign Identifier
   * @member {Number} campaignId
   */
  exports.prototype['campaignId'] = undefined;
  /**
   * UTC date and time at which the link should start showing up to get to the page (on the profile page, in the app, ...)
   * @member {Date} linkVisibleStartDateUtc
   */
  exports.prototype['linkVisibleStartDateUtc'] = undefined;
  /**
   * UTC date and time at which the link should stop showing up to get to the page (on the profile page, in the app, ...)
   * @member {Date} linkVisibleEndDateUtc
   */
  exports.prototype['linkVisibleEndDateUtc'] = undefined;



  return exports;
}));


