/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GeocacheLogType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GeocacheLogType'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.PostLogDraft = factory(root.GeocachingApiV10.ApiClient, root.GeocachingApiV10.GeocacheLogType);
  }
}(this, function(ApiClient, GeocacheLogType) {
  'use strict';




  /**
   * The PostLogDraft model module.
   * @module model/PostLogDraft
   * @version v1
   */

  /**
   * Constructs a new <code>PostLogDraft</code>.
   * @alias module:model/PostLogDraft
   * @class
   * @param geocacheCode {String} 
   */
  var exports = function(geocacheCode) {
    var _this = this;


    _this['geocacheCode'] = geocacheCode;






  };

  /**
   * Constructs a <code>PostLogDraft</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostLogDraft} obj Optional instance to populate.
   * @return {module:model/PostLogDraft} The populated <code>PostLogDraft</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('guid')) {
        obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
      }
      if (data.hasOwnProperty('geocacheCode')) {
        obj['geocacheCode'] = ApiClient.convertToType(data['geocacheCode'], 'String');
      }
      if (data.hasOwnProperty('logType')) {
        obj['logType'] = ApiClient.convertToType(data['logType'], 'String');
      }
      if (data.hasOwnProperty('geocacheLogType')) {
        obj['geocacheLogType'] = GeocacheLogType.constructFromObject(data['geocacheLogType']);
      }
      if (data.hasOwnProperty('note')) {
        obj['note'] = ApiClient.convertToType(data['note'], 'String');
      }
      if (data.hasOwnProperty('loggedDateUtc')) {
        obj['loggedDateUtc'] = ApiClient.convertToType(data['loggedDateUtc'], 'Date');
      }
      if (data.hasOwnProperty('loggedDate')) {
        obj['loggedDate'] = ApiClient.convertToType(data['loggedDate'], 'Date');
      }
      if (data.hasOwnProperty('useFavoritePoint')) {
        obj['useFavoritePoint'] = ApiClient.convertToType(data['useFavoritePoint'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} guid
   */
  exports.prototype['guid'] = undefined;
  /**
   * @member {String} geocacheCode
   */
  exports.prototype['geocacheCode'] = undefined;
  /**
   * @member {String} logType
   */
  exports.prototype['logType'] = undefined;
  /**
   * @member {module:model/GeocacheLogType} geocacheLogType
   */
  exports.prototype['geocacheLogType'] = undefined;
  /**
   * @member {String} note
   */
  exports.prototype['note'] = undefined;
  /**
   * @member {Date} loggedDateUtc
   */
  exports.prototype['loggedDateUtc'] = undefined;
  /**
   * @member {Date} loggedDate
   */
  exports.prototype['loggedDate'] = undefined;
  /**
   * @member {Boolean} useFavoritePoint
   */
  exports.prototype['useFavoritePoint'] = undefined;



  return exports;
}));


