/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GeocacheLog', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GeocacheLog'), require('./Image'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.PromotedDraft = factory(root.GeocachingApiV10.ApiClient, root.GeocachingApiV10.GeocacheLog, root.GeocachingApiV10.Image);
  }
}(this, function(ApiClient, GeocacheLog, Image) {
  'use strict';




  /**
   * The PromotedDraft model module.
   * @module model/PromotedDraft
   * @version v1
   */

  /**
   * Constructs a new <code>PromotedDraft</code>.
   * @alias module:model/PromotedDraft
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PromotedDraft</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PromotedDraft} obj Optional instance to populate.
   * @return {module:model/PromotedDraft} The populated <code>PromotedDraft</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('geocacheLog')) {
        obj['geocacheLog'] = GeocacheLog.constructFromObject(data['geocacheLog']);
      }
      if (data.hasOwnProperty('successfulImages')) {
        obj['successfulImages'] = ApiClient.convertToType(data['successfulImages'], [Image]);
      }
      if (data.hasOwnProperty('failedImages')) {
        obj['failedImages'] = ApiClient.convertToType(data['failedImages'], [Image]);
      }
      if (data.hasOwnProperty('favoritePointApplied')) {
        obj['favoritePointApplied'] = ApiClient.convertToType(data['favoritePointApplied'], 'Boolean');
      }
      if (data.hasOwnProperty('draftDeleted')) {
        obj['draftDeleted'] = ApiClient.convertToType(data['draftDeleted'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GeocacheLog} geocacheLog
   */
  exports.prototype['geocacheLog'] = undefined;
  /**
   * @member {Array.<module:model/Image>} successfulImages
   */
  exports.prototype['successfulImages'] = undefined;
  /**
   * @member {Array.<module:model/Image>} failedImages
   */
  exports.prototype['failedImages'] = undefined;
  /**
   * @member {Boolean} favoritePointApplied
   */
  exports.prototype['favoritePointApplied'] = undefined;
  /**
   * @member {Boolean} draftDeleted
   */
  exports.prototype['draftDeleted'] = undefined;



  return exports;
}));


