/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Coordinates'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Coordinates'));
  } else {
    // Browser globals (root is window)
    if (!root.GeocachingApiV10) {
      root.GeocachingApiV10 = {};
    }
    root.GeocachingApiV10.UserWaypoint = factory(root.GeocachingApiV10.ApiClient, root.GeocachingApiV10.Coordinates);
  }
}(this, function(ApiClient, Coordinates) {
  'use strict';




  /**
   * The UserWaypoint model module.
   * @module model/UserWaypoint
   * @version v1
   */

  /**
   * Constructs a new <code>UserWaypoint</code>.
   * @alias module:model/UserWaypoint
   * @class
   * @param isCorrectedCoordinates {Boolean} 
   * @param coordinates {module:model/Coordinates} 
   * @param geocacheCode {String} 
   */
  var exports = function(isCorrectedCoordinates, coordinates, geocacheCode) {
    var _this = this;



    _this['isCorrectedCoordinates'] = isCorrectedCoordinates;
    _this['coordinates'] = coordinates;
    _this['geocacheCode'] = geocacheCode;
  };

  /**
   * Constructs a <code>UserWaypoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserWaypoint} obj Optional instance to populate.
   * @return {module:model/UserWaypoint} The populated <code>UserWaypoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('referenceCode')) {
        obj['referenceCode'] = ApiClient.convertToType(data['referenceCode'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('isCorrectedCoordinates')) {
        obj['isCorrectedCoordinates'] = ApiClient.convertToType(data['isCorrectedCoordinates'], 'Boolean');
      }
      if (data.hasOwnProperty('coordinates')) {
        obj['coordinates'] = Coordinates.constructFromObject(data['coordinates']);
      }
      if (data.hasOwnProperty('geocacheCode')) {
        obj['geocacheCode'] = ApiClient.convertToType(data['geocacheCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} referenceCode
   */
  exports.prototype['referenceCode'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Boolean} isCorrectedCoordinates
   */
  exports.prototype['isCorrectedCoordinates'] = undefined;
  /**
   * @member {module:model/Coordinates} coordinates
   */
  exports.prototype['coordinates'] = undefined;
  /**
   * @member {String} geocacheCode
   */
  exports.prototype['geocacheCode'] = undefined;



  return exports;
}));


