/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiV10);
  }
}(this, function(expect, ApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiV10.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new ApiV10.User();
      //expect(instance).to.be.a(ApiV10.User);
    });

    it('should have the property avatarUrl (base name: "avatarUrl")', function() {
      // uncomment below and update the code to test the property avatarUrl
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property bannerUrl (base name: "bannerUrl")', function() {
      // uncomment below and update the code to test the property bannerUrl
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property favoritePoints (base name: "favoritePoints")', function() {
      // uncomment below and update the code to test the property favoritePoints
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property findCount (base name: "findCount")', function() {
      // uncomment below and update the code to test the property findCount
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property geocacheFindCounts (base name: "geocacheFindCounts")', function() {
      // uncomment below and update the code to test the property geocacheFindCounts
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property geocacheHideCounts (base name: "geocacheHideCounts")', function() {
      // uncomment below and update the code to test the property geocacheHideCounts
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property geocacheLimits (base name: "geocacheLimits")', function() {
      // uncomment below and update the code to test the property geocacheLimits
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property hideCount (base name: "hideCount")', function() {
      // uncomment below and update the code to test the property hideCount
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property homeCoordinates (base name: "homeCoordinates")', function() {
      // uncomment below and update the code to test the property homeCoordinates
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property isFriend (base name: "isFriend")', function() {
      // uncomment below and update the code to test the property isFriend
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property joinedDateUtc (base name: "joinedDateUtc")', function() {
      // uncomment below and update the code to test the property joinedDateUtc
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property membershipLevelId (base name: "membershipLevelId")', function() {
      // uncomment below and update the code to test the property membershipLevelId
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property optedInFriendSharing (base name: "optedInFriendSharing")', function() {
      // uncomment below and update the code to test the property optedInFriendSharing
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property profileText (base name: "profileText")', function() {
      // uncomment below and update the code to test the property profileText
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property referenceCode (base name: "referenceCode")', function() {
      // uncomment below and update the code to test the property referenceCode
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property trackableFindCounts (base name: "trackableFindCounts")', function() {
      // uncomment below and update the code to test the property trackableFindCounts
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property trackableOwnedCounts (base name: "trackableOwnedCounts")', function() {
      // uncomment below and update the code to test the property trackableOwnedCounts
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new ApiV10.User();
      //expect(instance).to.be();
    });

  });

}));
