/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HQPromotionMetadata from '../model/HQPromotionMetadata';

/**
* HQPromotions service.
* @module api/HQPromotionsApi
* @version v1
*/
export default class HQPromotionsApi {

    /**
    * Constructs a new HQPromotionsApi. 
    * @alias module:api/HQPromotionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Returns a list of metadata for currently visible and upcoming Geocaching HQ promotions
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/HQPromotionMetadata>} and HTTP response
     */
    hQPromotionsGetWithHttpInfo(apiVersion) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling hQPromotionsGet");
      }

      let pathParams = {
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = [HQPromotionMetadata];
      return this.apiClient.callApi(
        '/v{api-version}/HQPromotions/metadata', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Returns a list of metadata for currently visible and upcoming Geocaching HQ promotions
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/HQPromotionMetadata>}
     */
    hQPromotionsGet(apiVersion) {
      return this.hQPromotionsGetWithHttpInfo(apiVersion)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
