/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BulkResponse from '../model/BulkResponse';
import Geocache from '../model/Geocache';
import GeocacheList from '../model/GeocacheList';
import ListGeocache from '../model/ListGeocache';
import PostGeocacheList from '../model/PostGeocacheList';
import PostListGeocache from '../model/PostListGeocache';

/**
* Lists service.
* @module api/ListsApi
* @version v1
*/
export default class ListsApi {

    /**
    * Constructs a new ListsApi. 
    * @alias module:api/ListsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add a geocache to a list
     * This method will return the geocache added.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {module:model/PostListGeocache} postListGeocache geocache to add to the list
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Geocache} and HTTP response
     */
    listsAddGeocacheWithHttpInfo(referenceCode, apiVersion, postListGeocache, opts) {
      opts = opts || {};
      let postBody = postListGeocache;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsAddGeocache");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsAddGeocache");
      }
      // verify the required parameter 'postListGeocache' is set
      if (postListGeocache === undefined || postListGeocache === null) {
        throw new Error("Missing the required parameter 'postListGeocache' when calling listsAddGeocache");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = ['application/json', 'application/json-patch+json', 'application/x-www-form-urlencoded', 'text/json'];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = Geocache;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}/geocaches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add a geocache to a list
     * This method will return the geocache added.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {module:model/PostListGeocache} postListGeocache geocache to add to the list
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Geocache}
     */
    listsAddGeocache(referenceCode, apiVersion, postListGeocache, opts) {
      return this.listsAddGeocacheWithHttpInfo(referenceCode, apiVersion, postListGeocache, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Add multiple geocaches to a list
     * This method will return the successful and failed geocache codes.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {Array.<String>} requestBody geocache reference codes to add to the list
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BulkResponse} and HTTP response
     */
    listsAddGeocachesWithHttpInfo(referenceCode, apiVersion, requestBody) {
      let postBody = requestBody;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsAddGeocaches");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsAddGeocaches");
      }
      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling listsAddGeocaches");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = ['application/json', 'application/json-patch+json', 'application/x-www-form-urlencoded', 'text/json'];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = BulkResponse;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}/bulkgeocaches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add multiple geocaches to a list
     * This method will return the successful and failed geocache codes.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {Array.<String>} requestBody geocache reference codes to add to the list
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BulkResponse}
     */
    listsAddGeocaches(referenceCode, apiVersion, requestBody) {
      return this.listsAddGeocachesWithHttpInfo(referenceCode, apiVersion, requestBody)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a list
     * This method will return the created geocache list.
     * @param {String} apiVersion The requested API version
     * @param {module:model/PostGeocacheList} postGeocacheList The list to add
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GeocacheList} and HTTP response
     */
    listsCreateListWithHttpInfo(apiVersion, postGeocacheList, opts) {
      opts = opts || {};
      let postBody = postGeocacheList;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsCreateList");
      }
      // verify the required parameter 'postGeocacheList' is set
      if (postGeocacheList === undefined || postGeocacheList === null) {
        throw new Error("Missing the required parameter 'postGeocacheList' when calling listsCreateList");
      }

      let pathParams = {
        'api-version': apiVersion
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = ['application/json', 'application/json-patch+json', 'application/x-www-form-urlencoded', 'text/json'];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = GeocacheList;
      return this.apiClient.callApi(
        '/v{api-version}/lists', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a list
     * This method will return the created geocache list.
     * @param {String} apiVersion The requested API version
     * @param {module:model/PostGeocacheList} postGeocacheList The list to add
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GeocacheList}
     */
    listsCreateList(apiVersion, postGeocacheList, opts) {
      return this.listsCreateListWithHttpInfo(apiVersion, postGeocacheList, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Remove a geocache from a list
     * This method will not return anything.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} geocacheReferenceCode unique identifier of the geocache to remove
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    listsDeleteGeocacheWithHttpInfo(referenceCode, geocacheReferenceCode, apiVersion) {
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsDeleteGeocache");
      }
      // verify the required parameter 'geocacheReferenceCode' is set
      if (geocacheReferenceCode === undefined || geocacheReferenceCode === null) {
        throw new Error("Missing the required parameter 'geocacheReferenceCode' when calling listsDeleteGeocache");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsDeleteGeocache");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'geocacheReferenceCode': geocacheReferenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}/geocaches/{geocacheReferenceCode}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Remove a geocache from a list
     * This method will not return anything.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} geocacheReferenceCode unique identifier of the geocache to remove
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    listsDeleteGeocache(referenceCode, geocacheReferenceCode, apiVersion) {
      return this.listsDeleteGeocacheWithHttpInfo(referenceCode, geocacheReferenceCode, apiVersion)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Remove a list
     * This method will not return anything.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    listsDeleteListWithHttpInfo(referenceCode, apiVersion) {
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsDeleteList");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsDeleteList");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Remove a list
     * This method will not return anything.
     * @param {String} referenceCode unique identifier of the list
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    listsDeleteList(referenceCode, apiVersion) {
      return this.listsDeleteListWithHttpInfo(referenceCode, apiVersion)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a list of geocaches for a specified list
     * This method will return a list of geocaches.
     * @param {String} referenceCode identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip how many geocaches to skip over (default to 0)
     * @param {Number} opts.take how many geocaches to retrieve (default to 10)
     * @param {Boolean} opts.lite whether to return lite geocaches or not (default to true)
     * @param {String} opts.fields fields you want to return, defaults to \"referenceCode\" (default to 'referenceCode')
     * @param {String} opts.expand fields to include with base geocache object (default to '')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ListGeocache>} and HTTP response
     */
    listsGetGeocachesWithHttpInfo(referenceCode, apiVersion, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsGetGeocaches");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsGetGeocaches");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
        'skip': opts['skip'],
        'take': opts['take'],
        'lite': opts['lite'],
        'fields': opts['fields'],
        'expand': opts['expand']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = [ListGeocache];
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}/geocaches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a list of geocaches for a specified list
     * This method will return a list of geocaches.
     * @param {String} referenceCode identifier of the list
     * @param {String} apiVersion The requested API version
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip how many geocaches to skip over (default to 0)
     * @param {Number} opts.take how many geocaches to retrieve (default to 10)
     * @param {Boolean} opts.lite whether to return lite geocaches or not (default to true)
     * @param {String} opts.fields fields you want to return, defaults to \"referenceCode\" (default to 'referenceCode')
     * @param {String} opts.expand fields to include with base geocache object (default to '')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ListGeocache>}
     */
    listsGetGeocaches(referenceCode, apiVersion, opts) {
      return this.listsGetGeocachesWithHttpInfo(referenceCode, apiVersion, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a list
     * This method will return a list.
     * @param {String} referenceCode The reference code of the list (example: BM25).
     * @param {String} apiVersion The requested API version
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GeocacheList} and HTTP response
     */
    listsGetListWithHttpInfo(referenceCode, apiVersion, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsGetList");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsGetList");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = GeocacheList;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a list
     * This method will return a list.
     * @param {String} referenceCode The reference code of the list (example: BM25).
     * @param {String} apiVersion The requested API version
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GeocacheList}
     */
    listsGetList(referenceCode, apiVersion, opts) {
      return this.listsGetListWithHttpInfo(referenceCode, apiVersion, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets a zipped file for a pocket query
     * This method will return a zipped file.
     * @param {String} referenceCode identifier of the pocket query
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Blob} and HTTP response
     */
    listsGetZippedPocketQueryWithHttpInfo(referenceCode, apiVersion) {
      let postBody = null;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsGetZippedPocketQuery");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsGetZippedPocketQuery");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = 'Blob';
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}/geocaches/zipped', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Gets a zipped file for a pocket query
     * This method will return a zipped file.
     * @param {String} referenceCode identifier of the pocket query
     * @param {String} apiVersion The requested API version
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Blob}
     */
    listsGetZippedPocketQuery(referenceCode, apiVersion) {
      return this.listsGetZippedPocketQueryWithHttpInfo(referenceCode, apiVersion)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Edit a list
     * This method will return the updated geocache list.
     * @param {String} referenceCode the unique identifier of the list (ex: BM100)
     * @param {String} apiVersion The requested API version
     * @param {module:model/GeocacheList} geocacheList The list to update
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GeocacheList} and HTTP response
     */
    listsUpdateListWithHttpInfo(referenceCode, apiVersion, geocacheList, opts) {
      opts = opts || {};
      let postBody = geocacheList;
      // verify the required parameter 'referenceCode' is set
      if (referenceCode === undefined || referenceCode === null) {
        throw new Error("Missing the required parameter 'referenceCode' when calling listsUpdateList");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling listsUpdateList");
      }
      // verify the required parameter 'geocacheList' is set
      if (geocacheList === undefined || geocacheList === null) {
        throw new Error("Missing the required parameter 'geocacheList' when calling listsUpdateList");
      }

      let pathParams = {
        'referenceCode': referenceCode,
        'api-version': apiVersion
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AccessToken'];
      let contentTypes = ['application/json', 'application/json-patch+json', 'application/x-www-form-urlencoded', 'text/json'];
      let accepts = ['application/json', 'application/json-patch+json', 'text/json'];
      let returnType = GeocacheList;
      return this.apiClient.callApi(
        '/v{api-version}/lists/{referenceCode}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Edit a list
     * This method will return the updated geocache list.
     * @param {String} referenceCode the unique identifier of the list (ex: BM100)
     * @param {String} apiVersion The requested API version
     * @param {module:model/GeocacheList} geocacheList The list to update
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Property fields you want to return, defaults to referenceCode (default to 'referenceCode')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GeocacheList}
     */
    listsUpdateList(referenceCode, apiVersion, geocacheList, opts) {
      return this.listsUpdateListWithHttpInfo(referenceCode, apiVersion, geocacheList, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
