/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GeocacheType from './GeocacheType';

/**
 * The GeocacheCount model module.
 * @module model/GeocacheCount
 * @version v1
 */
class GeocacheCount {
    /**
     * Constructs a new <code>GeocacheCount</code>.
     * @alias module:model/GeocacheCount
     */
    constructor() { 
        
        GeocacheCount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GeocacheCount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GeocacheCount} obj Optional instance to populate.
     * @return {module:model/GeocacheCount} The populated <code>GeocacheCount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeocacheCount();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('geocacheType')) {
                obj['geocacheType'] = GeocacheType.constructFromObject(data['geocacheType']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
GeocacheCount.prototype['count'] = undefined;

/**
 * @member {module:model/GeocacheType} geocacheType
 */
GeocacheCount.prototype['geocacheType'] = undefined;






export default GeocacheCount;

