/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Sponsor model module.
 * @module model/Sponsor
 * @version v1
 */
class Sponsor {
    /**
     * Constructs a new <code>Sponsor</code>.
     * @alias module:model/Sponsor
     */
    constructor() { 
        
        Sponsor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Sponsor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sponsor} obj Optional instance to populate.
     * @return {module:model/Sponsor} The populated <code>Sponsor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sponsor();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('relatedWebPage')) {
                obj['relatedWebPage'] = ApiClient.convertToType(data['relatedWebPage'], 'String');
            }
            if (data.hasOwnProperty('relatedWebPageText')) {
                obj['relatedWebPageText'] = ApiClient.convertToType(data['relatedWebPageText'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Sponsor.prototype['name'] = undefined;

/**
 * @member {String} relatedWebPage
 */
Sponsor.prototype['relatedWebPage'] = undefined;

/**
 * @member {String} relatedWebPageText
 */
Sponsor.prototype['relatedWebPageText'] = undefined;






export default Sponsor;

