/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrackableLogType model module.
 * @module model/TrackableLogType
 * @version v1
 */
class TrackableLogType {
    /**
     * Constructs a new <code>TrackableLogType</code>.
     * @alias module:model/TrackableLogType
     */
    constructor() { 
        
        TrackableLogType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrackableLogType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrackableLogType} obj Optional instance to populate.
     * @return {module:model/TrackableLogType} The populated <code>TrackableLogType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackableLogType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
TrackableLogType.prototype['id'] = undefined;

/**
 * @member {String} imageUrl
 */
TrackableLogType.prototype['imageUrl'] = undefined;

/**
 * @member {String} name
 */
TrackableLogType.prototype['name'] = undefined;






export default TrackableLogType;

