/**
 * API v1.0
 * API version 1.0.
 *
 * The version of the OpenAPI document: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserReference model module.
 * @module model/UserReference
 * @version v1
 */
class UserReference {
    /**
     * Constructs a new <code>UserReference</code>.
     * @alias module:model/UserReference
     */
    constructor() { 
        
        UserReference.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserReference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserReference} obj Optional instance to populate.
     * @return {module:model/UserReference} The populated <code>UserReference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserReference();

            if (data.hasOwnProperty('avatarUrl')) {
                obj['avatarUrl'] = ApiClient.convertToType(data['avatarUrl'], 'String');
            }
            if (data.hasOwnProperty('referenceCode')) {
                obj['referenceCode'] = ApiClient.convertToType(data['referenceCode'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} avatarUrl
 */
UserReference.prototype['avatarUrl'] = undefined;

/**
 * @member {String} referenceCode
 */
UserReference.prototype['referenceCode'] = undefined;

/**
 * @member {String} username
 */
UserReference.prototype['username'] = undefined;






export default UserReference;

