/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.GeocacheLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GeocacheLog', function() {
    it('should create an instance of GeocacheLog', function() {
      // uncomment below and update the code to test GeocacheLog
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be.a(GeocachingApiV10.GeocacheLog);
    });

    it('should have the property referenceCode (base name: "referenceCode")', function() {
      // uncomment below and update the code to test the property referenceCode
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property ownerCode (base name: "ownerCode")', function() {
      // uncomment below and update the code to test the property ownerCode
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property imageCount (base name: "imageCount")', function() {
      // uncomment below and update the code to test the property imageCount
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property isEncoded (base name: "isEncoded")', function() {
      // uncomment below and update the code to test the property isEncoded
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property isArchived (base name: "isArchived")', function() {
      // uncomment below and update the code to test the property isArchived
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property geocacheName (base name: "geocacheName")', function() {
      // uncomment below and update the code to test the property geocacheName
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property ianaTimezoneId (base name: "ianaTimezoneId")', function() {
      // uncomment below and update the code to test the property ianaTimezoneId
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property loggedDate (base name: "loggedDate")', function() {
      // uncomment below and update the code to test the property loggedDate
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property geocacheLogType (base name: "geocacheLogType")', function() {
      // uncomment below and update the code to test the property geocacheLogType
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property updatedCoordinates (base name: "updatedCoordinates")', function() {
      // uncomment below and update the code to test the property updatedCoordinates
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property geocacheCode (base name: "geocacheCode")', function() {
      // uncomment below and update the code to test the property geocacheCode
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

    it('should have the property usedFavoritePoint (base name: "usedFavoritePoint")', function() {
      // uncomment below and update the code to test the property usedFavoritePoint
      //var instance = new GeocachingApiV10.GeocacheLog();
      //expect(instance).to.be();
    });

  });

}));
