/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/geocaching-api-v10'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/geocaching-api-v10'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.LogDraft();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LogDraft', function() {
    it('should create an instance of LogDraft', function() {
      // uncomment below and update the code to test LogDraft
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be.a(GeocachingApiV10.LogDraft);
    });

    it('should have the property referenceCode (base name: "referenceCode")', function() {
      // uncomment below and update the code to test the property referenceCode
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property imageCount (base name: "imageCount")', function() {
      // uncomment below and update the code to test the property imageCount
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property geocacheCode (base name: "geocacheCode")', function() {
      // uncomment below and update the code to test the property geocacheCode
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property logType (base name: "logType")', function() {
      // uncomment below and update the code to test the property logType
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property geocacheLogType (base name: "geocacheLogType")', function() {
      // uncomment below and update the code to test the property geocacheLogType
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property loggedDateUtc (base name: "loggedDateUtc")', function() {
      // uncomment below and update the code to test the property loggedDateUtc
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property loggedDate (base name: "loggedDate")', function() {
      // uncomment below and update the code to test the property loggedDate
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property useFavoritePoint (base name: "useFavoritePoint")', function() {
      // uncomment below and update the code to test the property useFavoritePoint
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

    it('should have the property geocacheName (base name: "geocacheName")', function() {
      // uncomment below and update the code to test the property geocacheName
      //var instance = new GeocachingApiV10.LogDraft();
      //expect(instance).to.be();
    });

  });

}));
