/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.TrackableLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrackableLog', function() {
    it('should create an instance of TrackableLog', function() {
      // uncomment below and update the code to test TrackableLog
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be.a(GeocachingApiV10.TrackableLog);
    });

    it('should have the property referenceCode (base name: "referenceCode")', function() {
      // uncomment below and update the code to test the property referenceCode
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property ownerCode (base name: "ownerCode")', function() {
      // uncomment below and update the code to test the property ownerCode
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property imageCount (base name: "imageCount")', function() {
      // uncomment below and update the code to test the property imageCount
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property geocacheName (base name: "geocacheName")', function() {
      // uncomment below and update the code to test the property geocacheName
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property trackableCode (base name: "trackableCode")', function() {
      // uncomment below and update the code to test the property trackableCode
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property geocacheCode (base name: "geocacheCode")', function() {
      // uncomment below and update the code to test the property geocacheCode
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property loggedDate (base name: "loggedDate")', function() {
      // uncomment below and update the code to test the property loggedDate
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property isRot13Encoded (base name: "isRot13Encoded")', function() {
      // uncomment below and update the code to test the property isRot13Encoded
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property typeId (base name: "typeId")', function() {
      // uncomment below and update the code to test the property typeId
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property trackableLogType (base name: "trackableLogType")', function() {
      // uncomment below and update the code to test the property trackableLogType
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

    it('should have the property coordinates (base name: "coordinates")', function() {
      // uncomment below and update the code to test the property coordinates
      //var instance = new GeocachingApiV10.TrackableLog();
      //expect(instance).to.be();
    });

  });

}));
