/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.Trackable();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Trackable', function() {
    it('should create an instance of Trackable', function() {
      // uncomment below and update the code to test Trackable
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be.a(GeocachingApiV10.Trackable);
    });

    it('should have the property referenceCode (base name: "referenceCode")', function() {
      // uncomment below and update the code to test the property referenceCode
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property iconUrl (base name: "iconUrl")', function() {
      // uncomment below and update the code to test the property iconUrl
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property goal (base name: "goal")', function() {
      // uncomment below and update the code to test the property goal
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property releasedDate (base name: "releasedDate")', function() {
      // uncomment below and update the code to test the property releasedDate
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property originCountry (base name: "originCountry")', function() {
      // uncomment below and update the code to test the property originCountry
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property allowedToBeCollected (base name: "allowedToBeCollected")', function() {
      // uncomment below and update the code to test the property allowedToBeCollected
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property ownerCode (base name: "ownerCode")', function() {
      // uncomment below and update the code to test the property ownerCode
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property holderCode (base name: "holderCode")', function() {
      // uncomment below and update the code to test the property holderCode
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property holder (base name: "holder")', function() {
      // uncomment below and update the code to test the property holder
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property inHolderCollection (base name: "inHolderCollection")', function() {
      // uncomment below and update the code to test the property inHolderCollection
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property currentGeocacheCode (base name: "currentGeocacheCode")', function() {
      // uncomment below and update the code to test the property currentGeocacheCode
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property isMissing (base name: "isMissing")', function() {
      // uncomment below and update the code to test the property isMissing
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property trackableType (base name: "trackableType")', function() {
      // uncomment below and update the code to test the property trackableType
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property imageCount (base name: "imageCount")', function() {
      // uncomment below and update the code to test the property imageCount
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property trackingNumber (base name: "trackingNumber")', function() {
      // uncomment below and update the code to test the property trackingNumber
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property currentGeocacheName (base name: "currentGeocacheName")', function() {
      // uncomment below and update the code to test the property currentGeocacheName
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property trackableLogs (base name: "trackableLogs")', function() {
      // uncomment below and update the code to test the property trackableLogs
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new GeocachingApiV10.Trackable();
      //expect(instance).to.be();
    });

  });

}));
