/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.UserData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserData', function() {
    it('should create an instance of UserData', function() {
      // uncomment below and update the code to test UserData
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be.a(GeocachingApiV10.UserData);
    });

    it('should have the property foundDate (base name: "foundDate")', function() {
      // uncomment below and update the code to test the property foundDate
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be();
    });

    it('should have the property dnfDate (base name: "dnfDate")', function() {
      // uncomment below and update the code to test the property dnfDate
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be();
    });

    it('should have the property correctedCoordinates (base name: "correctedCoordinates")', function() {
      // uncomment below and update the code to test the property correctedCoordinates
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be();
    });

    it('should have the property isFavorited (base name: "isFavorited")', function() {
      // uncomment below and update the code to test the property isFavorited
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new GeocachingApiV10.UserData();
      //expect(instance).to.be();
    });

  });

}));
