/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/geocaching-api-v10'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/geocaching-api-v10'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.LogDraftsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LogDraftsApi', function() {
    describe('logDraftsAddImage', function() {
      it('should call logDraftsAddImage successfully', function(done) {
        //uncomment below and update the code to test logDraftsAddImage
        //instance.logDraftsAddImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsCreateDraft', function() {
      it('should call logDraftsCreateDraft successfully', function(done) {
        //uncomment below and update the code to test logDraftsCreateDraft
        //instance.logDraftsCreateDraft(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsDeleteDraft', function() {
      it('should call logDraftsDeleteDraft successfully', function(done) {
        //uncomment below and update the code to test logDraftsDeleteDraft
        //instance.logDraftsDeleteDraft(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsGetDraft', function() {
      it('should call logDraftsGetDraft successfully', function(done) {
        //uncomment below and update the code to test logDraftsGetDraft
        //instance.logDraftsGetDraft(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsGetUserDrafts', function() {
      it('should call logDraftsGetUserDrafts successfully', function(done) {
        //uncomment below and update the code to test logDraftsGetUserDrafts
        //instance.logDraftsGetUserDrafts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsPromoteToGeocacheLog', function() {
      it('should call logDraftsPromoteToGeocacheLog successfully', function(done) {
        //uncomment below and update the code to test logDraftsPromoteToGeocacheLog
        //instance.logDraftsPromoteToGeocacheLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logDraftsUpdateDraft', function() {
      it('should call logDraftsUpdateDraft successfully', function(done) {
        //uncomment below and update the code to test logDraftsUpdateDraft
        //instance.logDraftsUpdateDraft(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
