/**
 * Geocaching API v1.0
 * Geocaching API version 1.0.
 *
 * OpenAPI spec version: v1
 * Contact: apihelp@geocaching.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/geocaching-api-v10'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/geocaching-api-v10'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GeocachingApiV10);
  }
}(this, function(expect, GeocachingApiV10) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GeocachingApiV10.TrackablesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrackablesApi', function() {
    describe('trackablesGetGeocoinTypes', function() {
      it('should call trackablesGetGeocoinTypes successfully', function(done) {
        //uncomment below and update the code to test trackablesGetGeocoinTypes
        //instance.trackablesGetGeocoinTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trackablesGetImages', function() {
      it('should call trackablesGetImages successfully', function(done) {
        //uncomment below and update the code to test trackablesGetImages
        //instance.trackablesGetImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trackablesGetTrackable', function() {
      it('should call trackablesGetTrackable successfully', function(done) {
        //uncomment below and update the code to test trackablesGetTrackable
        //instance.trackablesGetTrackable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trackablesGetTrackableLogs', function() {
      it('should call trackablesGetTrackableLogs successfully', function(done) {
        //uncomment below and update the code to test trackablesGetTrackableLogs
        //instance.trackablesGetTrackableLogs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trackablesGetUserTrackables', function() {
      it('should call trackablesGetUserTrackables successfully', function(done) {
        //uncomment below and update the code to test trackablesGetUserTrackables
        //instance.trackablesGetUserTrackables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
